# Generated by Django 4.1.10 on 2024-01-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_add_postal_code_result_saved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
    ]
