# Generated by Django 4.1.10 on 2024-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_filled_for_fun",
            field=models.BooleanField(default=False),
        ),
    ]
