# Generated by Django 4.1.10 on 2024-01-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_profile_result_can_be_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
