# Generated by Django 4.1.10 on 2024-02-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_rename_age_profile_year_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("X", "X")],
                max_length=2,
                null=True,
            ),
        ),
    ]
