# Generated by Django 4.1.13 on 2024-04-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_user_has_subscribed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_filled_for_fun",
        ),
    ]
