# Generated by Django 4.1.10 on 2023-09-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, null=True)),
                ("value_fi", models.CharField(max_length=255, null=True)),
                ("value_sv", models.CharField(max_length=255, null=True)),
                ("value_en", models.CharField(max_length=255, null=True)),
                ("affect_result", models.BooleanField(default=True)),
                ("order_number", models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                "ordering": ["question__number", "sub_question__question__number"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=3, null=True)),
                ("question", models.CharField(max_length=255, null=True)),
                ("question_fi", models.CharField(max_length=255, null=True)),
                ("question_sv", models.CharField(max_length=255, null=True)),
                ("question_en", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("description_fi", models.CharField(max_length=255, null=True)),
                ("description_sv", models.CharField(max_length=255, null=True)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("number_of_choices", models.CharField(default="1", max_length=2)),
                (
                    "number_of_sub_question_choices",
                    models.PositiveSmallIntegerField(default=1),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=64, null=True)),
                ("topic_fi", models.CharField(max_length=64, null=True)),
                ("topic_sv", models.CharField(max_length=64, null=True)),
                ("topic_en", models.CharField(max_length=64, null=True)),
                ("value", models.CharField(max_length=64, null=True)),
                ("value_fi", models.CharField(max_length=64, null=True)),
                ("value_sv", models.CharField(max_length=64, null=True)),
                ("value_en", models.CharField(max_length=64, null=True)),
                ("description", models.TextField(null=True)),
                ("description_fi", models.TextField(null=True)),
                ("description_sv", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, null=True)),
                ("description_fi", models.CharField(max_length=255, null=True)),
                ("description_sv", models.CharField(max_length=255, null=True)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("additional_description", models.CharField(max_length=255, null=True)),
                (
                    "additional_description_fi",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "additional_description_sv",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "additional_description_en",
                    models.CharField(max_length=255, null=True),
                ),
                ("order_number", models.PositiveSmallIntegerField(null=True)),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_questions",
                        to="profiles.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question__number"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_conditions",
                    models.ManyToManyField(
                        related_name="option_conditions", to="profiles.option"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="profiles.question",
                    ),
                ),
                (
                    "question_condition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_conditions",
                        to="profiles.question",
                    ),
                ),
                (
                    "sub_question_condition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_question_conditions",
                        to="profiles.subquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="profiles.question",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="results",
            field=models.ManyToManyField(related_name="options", to="profiles.result"),
        ),
        migrations.AddField(
            model_name="option",
            name="sub_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="profiles.subquestion",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="profiles.option",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("user", "option"), name="unique_user_and_option"
            ),
        ),
    ]
