# Generated by Django 4.1.10 on 2023-09-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0002_add_mandatory_number_of_sub_question_answers_to_question",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="profiles.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="sub_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="profiles.subquestion",
            ),
        ),
    ]
