# Generated by Django 4.1.10 on 2023-09-22 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_add_question_and_sub_question_to_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="number_of_choices",
            new_name="number_of_options_to_choose",
        ),
    ]
