# Generated by Django 4.1.10 on 2023-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_add_model_postalcode_and_postalcoderesult"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalCodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        choices=[("Home", "Home"), ("Optional", "Optional")],
                        default="Optional",
                        max_length=8,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
