# Generated by Django 4.1.10 on 2023-12-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_alter_postalcoderesult_postal_code_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioncondition",
            name="option_conditions",
            field=models.ManyToManyField(
                related_name="question_conditions", to="profiles.option"
            ),
        ),
        migrations.AlterField(
            model_name="questioncondition",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_conditions",
                to="profiles.question",
            ),
        ),
        migrations.AlterField(
            model_name="questioncondition",
            name="question_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_question_conditions",
                to="profiles.question",
            ),
        ),
        migrations.AlterField(
            model_name="questioncondition",
            name="sub_question_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_conditions",
                to="profiles.subquestion",
            ),
        ),
    ]
