# Generated by Django 4.1.10 on 2023-12-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_question_condition_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubQuestionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_question_conditions",
                        to="profiles.option",
                    ),
                ),
                (
                    "sub_question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_question_conditions",
                        to="profiles.subquestion",
                    ),
                ),
            ],
        ),
    ]
