# Generated by Django 4.1.10 on 2024-02-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_subquestioncondition"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique_user_and_option",
        ),
        migrations.AlterField(
            model_name="answer",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="profiles.option",
            ),
        ),
    ]
