# Generated by Django 4.1.10 on 2024-02-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_remove_answer_unique_user_and_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="other",
            field=models.TextField(blank=True, null=True),
        ),
    ]
