# Generated by Django 4.1.10 on 2024-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_answer_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="is_other",
            field=models.BooleanField(default=False, verbose_name="is other textfield"),
        ),
    ]
