# Generated by Django 4.2 on 2024-02-15 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_alter_option_options_remove_result_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
    ]
