# Generated by Django 4.2 on 2024-02-29 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_answer_create_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postalcoderesult",
            options={"ordering": ["postal_code", "postal_code_type"]},
        ),
    ]
