# Generated by Django 4.2 on 2024-02-29 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_postalcoderesult_add_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questioncondition",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="subquestioncondition",
            options={"ordering": ["id"]},
        ),
    ]
