# Generated by Django 4.2 on 2024-02-29 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_questioncondition_subquestion_condition_add_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postalcode",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="postalcodetype",
            options={"ordering": ["id"]},
        ),
    ]
