# Generated by Django 4.1.13 on 2024-04-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_result_num_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CumulativeResultCount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profiles.result",),
        ),
    ]
