version: '3.4'

services:
    postgres:
        build: ./docker/postgres/
        environment:
            - POSTGRES_USER=mobilityprofile
            - POSTGRES_PASSWORD=mobilityprofile
            - POSTGRES_DB=mobilityprofile
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data 
 
    memcached:
        image: memcached:latest
        command: ["-I", "4m"]
        ports:
        - "11211:11211"
        restart: always

    mpbackend:
        image: mpbackend
        build:
            context: .
            dockerfile: ./docker/mpbackend/Dockerfile            
            args:
                - REQUIREMENTS_FILE=requirements.txt
        ports:
            - 8000:8000
        environment:   
            - APPLY_MIGRATIONS=true
            
        command: start_django_development_server

        env_file:
            - config_dev.env
        volumes:
            - mpbackend:/mpbackend
            - static:/mpbackend/static/   
        restart: on-failure
        depends_on:
            postgres:
                condition: service_started
        
   
volumes:
    postgres-data:
    mpbackend:
    static:


